### PR TITLE
update mooseError to not use << - prep for new error/warn funcs

### PR DESCRIPTION
**Pull request by rwcarlsen**

### CODE REVIEW

**Comment by rwcarlsen** [comment]
Failed because CMake version on CI not new enough.

**Comment by rwcarlsen** [comment]
@dschwen - this is needed to get magpie ready for the new error/warn functions.  Then we'll need to update the mytrim submodule for magpie.

**Comment by dschwen** [comment]
Weird. The CI testing used to pass.

**Comment by dschwen** [comment]
Oh, I see, the jsoncpp (submodule) people have bumped their min required CMake version...

**Comment by dschwen** [comment]
Thx!

**Pull request merged**
